# Generated by Django 4.1.3 on 2022-11-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_marks_feedback_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='venue',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='venue',
            new_name='marks',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='venue',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Marks',
            new_name='marks',
        ),
    ]
