# Generated by Django 4.1.1 on 2022-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_venue_admission_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
