# Generated by Django 4.1.1 on 2022-11-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_admission_student_remove_marks_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='Student_name',
        ),
        migrations.AddField(
            model_name='admission',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AddField(
            model_name='marks',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='Reg_no',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marks',
            name='Reg_no',
            field=models.CharField(max_length=12),
        ),
    ]
